POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "admin",
    "password": "admin",  
    "gender": true,
    "fullName": "Do vinh ky"

}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
GET http://localhost:5000/api/auth
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0ODYwM2U1NzcxZTU1NGUzNDMzNGYiLCJpYXQiOjE2NzkwNjY5OTR9.u5S9Mu-ZUxVeJzjTXjY6wZVJfCj7mUm9Gn-zX5DgbRg

{
    "phoneNumber":"0123456789",
    "gender": true,
    "fullName": "Do vinh ky"

}

###
POST http://localhost:5000/api/category
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0ODYwM2U1NzcxZTU1NGUzNDMzNGYiLCJpYXQiOjE2NzkwNjk5NDR9.sxZieqvgKs7ZrBglasit4yooMxfndeHxBcb3Mx8CSjM

{
    "category":"Iphone"
}

###