POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "thanhdien",
    "password": "thanhdien",  
    "gender": true,
    "fullName": "Le Thanh Dien"

}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "thanhdien",
    "password": "thanhdien"
}

###
PUT http://localhost:5000/api/auth
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0ODYwM2U1NzcxZTU1NGUzNDMzNGYiLCJpYXQiOjE2NzkzMDU1NTN9.bqn2CLYb_lVC_Iz4uLlwjcsY8nfLI-ee7ca3FpnxFaw

{
    "phoneNumber":"0123456789",
    "gender": true,
    "fullName": "Do vinh ky2"
}


# Category

###
POST http://localhost:5000/api/category
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0ODYwM2U1NzcxZTU1NGUzNDMzNGYiLCJpYXQiOjE2NzkwNjk5NDR9.sxZieqvgKs7ZrBglasit4yooMxfndeHxBcb3Mx8CSjM

{
    "category":"Tablet"
}

###

GET http://localhost:5000/api/category
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0ODYwM2U1NzcxZTU1NGUzNDMzNGYiLCJpYXQiOjE2NzkwNjk5NDR9.sxZieqvgKs7ZrBglasit4yooMxfndeHxBcb3Mx8CSjM



# Carts
###
POST http://localhost:5000/api/carts/64171575382b9e02f5d501ae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0ODYwM2U1NzcxZTU1NGUzNDMzNGYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Nzk0NjUwNDN9.GC_MxeRwKrHxY4OHenq00s28ijPr8H33fLLvLunJ1E8

{
    "quantity": "3"
}

###
GET http://localhost:5000/api/carts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFhOGMxMWRiZDJkZGZlZjQ3YTg1ZDYiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjc5NDY5NjQyfQ.ogjpa9Lubcjwq_wjlKRLibFQikFx0E3cCsMawLunngQ

###
PUT http://localhost:5000/api/carts/641a92f112c88b241796fe81
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFhOGMxMWRiZDJkZGZlZjQ3YTg1ZDYiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjc5NDY5NjQyfQ.ogjpa9Lubcjwq_wjlKRLibFQikFx0E3cCsMawLunngQ

{
    "quantity": 5
}

###
DELETE http://localhost:5000/api/carts/641a92f112c88b241796fe81
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFhOGMxMWRiZDJkZGZlZjQ3YTg1ZDYiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjc5NDY5NjQyfQ.ogjpa9Lubcjwq_wjlKRLibFQikFx0E3cCsMawLunngQ
